# Generated by Django 4.2.3 on 2023-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='orederitem',
            name='size',
            field=models.CharField(choices=[('T-SHIRT', (('S', 's'), ('M', 'm'), ('L', 'l'), ('XL', 'xl'), ('2XL', '2xl'), ('3XL', '3xl'))), ('SHOES', (('EU 39', 'EU 39'), ('EU 40', 'EU 40'), ('EU 41', 'EU 41'), ('EU 42', 'EU 42'), ('EU 43', 'EU 43'), ('EU 44', 'EU 44')))], default='S', max_length=50),
        ),
    ]
