# Generated by Django 4.2.3 on 2023-07-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_size_orederitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orederitem',
            name='color',
            field=models.CharField(choices=[('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('GRAY', 'GRAY')], default='WHITE', max_length=50),
        ),
        migrations.AlterField(
            model_name='orederitem',
            name='size',
            field=models.CharField(choices=[('T-SHIRT', (('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'))), ('SHOES', (('EU 39', 'EU 39'), ('EU 40', 'EU 40'), ('EU 41', 'EU 41'), ('EU 42', 'EU 42'), ('EU 43', 'EU 43'), ('EU 44', 'EU 44')))], default='S', max_length=50),
        ),
    ]
