# Generated by Django 4.2.3 on 2023-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shippingaddress_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='oreder',
            name='oreder_id',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oreder',
            name='paypal_oreder_id',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='oreder',
            name='total',
            field=models.FloatField(max_length=300, null=True),
        ),
    ]
