# Generated by Django 4.2.3 on 2023-07-25 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_oreder_oreder_id_oreder_paypal_oreder_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oreder',
            old_name='oreder_id',
            new_name='stripe_oreder_id',
        ),
    ]
